##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/emasicol/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp blogs.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp cv.html $DEPLOYPATH
    - /bin/cp projects.html $DEPLOYPATH